---
title: "amazon employee access"
author: "J U L I A"
format: html
editor: visual
---

```{r}
library(vroom)
library(lubridate)
library(tidyverse)
library(tidymodels)
library(recipes)
library(embed)
library(dials)
library(kknn)

amazontrain <- vroom("C:/Users/julia/OneDrive - Brigham Young University/Desktop/stat 348/amazon-employee-access/amazon-employee-access-challenge/train.csv")
amazontrain <- amazontrain %>% mutate(ACTION = factor(ACTION))

amazontest <- vroom("C:/Users/julia/OneDrive - Brigham Young University/Desktop/stat 348/amazon-employee-access/amazon-employee-access-challenge/test.csv")

```

convert to factors and make recipe

```{r}

id_cols <- c("RESOURCE","MGR_ID","ROLE_ROLLUP_1","ROLE_ROLLUP_2",
             "ROLE_DEPTNAME","ROLE_TITLE","ROLE_FAMILY_DESC",
             "ROLE_FAMILY","ROLE_CODE")

amazontrain <- amazontrain %>% mutate(across(all_of(id_cols), as.factor))
amazontest  <- amazontest  %>% mutate(across(all_of(id_cols), as.factor))

amazontrain <- amazontrain %>%
  mutate_if(is.character, as.factor) %>%   # convert text to factors
  mutate_if(is.numeric, as.factor)         # convert IDs to factors if they’re really categories

amazonrecipetrain <- recipe(ACTION ~ ., data = amazontrain) %>%
  step_other(all_nominal_predictors(), threshold = 0.01) %>% 
  step_unknown(all_nominal_predictors()) %>%        # handles unseen test levels
  step_lencode_mixed(all_nominal_predictors(), outcome = vars(ACTION))

```

```{r}
amazon_knn_model <- nearest_neighbor(neighbors=3) %>% 
  set_mode("classification") %>% 
  set_engine("kknn")
```

```{r}
amazon_wf <- workflow() %>%
  add_recipe(amazonrecipetrain) %>%
  add_model(amazon_knn_model)
```


```{r}

final_wf <- amazon_wf %>% 
  fit(data=amazontrain)
```

```{r}

preds <- predict(final_wf, new_data=amazontest, type = "prob") %>% 
  rename(ACTION=.pred_1)
```

```{r}
results <- tibble(id = amazontest$id, ACTION = preds$ACTION)

vroom_write(results, 
            "C:/Users/julia/OneDrive - Brigham Young University/Desktop/stat 348/amazon-employee-access/knnresults.csv",
            delim = ",")

```
